use tsify::declare;
use wasm_bindgen::prelude::wasm_bindgen;

// 2023:
// These enum definitions are only used to generate a typescript file, they should not be used in rust code.
// They should match the definitions in ability_types.rs

// 2025:
// The enums generated by this file MUST appear above the type definition of the same name generated by tsify. 
// For example, enum Ticket must appear before the declaration of type Ticket.
// I have added the underscore to this file to try to make it appear alphabetically first.
//
// I have fixed this issue using the typescript_custom_section strings. 
// However, ideally each enum should just have a normal wasm_bindgen tag on top of it, with no typescript_custom_section. 
// If i can find a way to guarantee that the enums would end up above types in the final file, then i should do this.
// 
// Example:
//
// #[wasm_bindgen]
// pub enum SubAbility {
// ...
// }

#[wasm_bindgen(typescript_custom_section)]
const TS_APPEND_CONTENT_SUBABILITY: &'static str = 
r#"export enum SubAbility {
    MainInk_Save = 0,
    SubInk_Save = 1,
    InkRecovery_Up = 2,
    HumanMove_Up = 3,
    SquidMove_Up = 4,
    SpecialIncrease_Up = 5,
    RespawnSpecialGauge_Save = 6,
    SpecialSpec_Up = 7,
    RespawnTime_Save = 8,
    JumpTime_Save = 9,
    SubSpec_Up = 10,
    OpInkEffect_Reduction = 11,
    SubEffect_Reduction = 12,
    Action_Up = 13,
}"#;
pub enum SubAbility {
    MainInk_Save = 0,
    SubInk_Save = 1,
    InkRecovery_Up = 2,
    HumanMove_Up = 3,
    SquidMove_Up = 4,
    SpecialIncrease_Up = 5,
    RespawnSpecialGauge_Save = 6,
    SpecialSpec_Up = 7,
    RespawnTime_Save = 8,
    JumpTime_Save = 9,
    SubSpec_Up =10,
    OpInkEffect_Reduction =11,
    SubEffect_Reduction =12,
    Action_Up =13,
}

#[wasm_bindgen(typescript_custom_section)]
const TS_APPEND_CONTENT_TICKET: &'static str = 
r#"export enum Ticket{
   MainInk_Save = 0,
   SubInk_Save = 1,
   InkRecovery_Up = 2,
   HumanMove_Up = 3,
   SquidMove_Up = 4,
   SpecialIncrease_Up = 5,
   RespawnSpecialGauge_Save = 6,
   SpecialSpec_Up = 7,
   RespawnTime_Save = 8,
   JumpTime_Save = 9,
   SubSpec_Up =10,
   OpInkEffect_Reduction =11,
   SubEffect_Reduction =12,
   Action_Up =13,
   None = 0xf
}"#;
pub enum Ticket{
   MainInk_Save = 0,
   SubInk_Save = 1,
   InkRecovery_Up = 2,
   HumanMove_Up = 3,
   SquidMove_Up = 4,
   SpecialIncrease_Up = 5,
   RespawnSpecialGauge_Save = 6,
   SpecialSpec_Up = 7,
   RespawnTime_Save = 8,
   JumpTime_Save = 9,
   SubSpec_Up =10,
   OpInkEffect_Reduction =11,
   SubEffect_Reduction =12,
   Action_Up =13,
   None = 0xf
}


/*#[wasm_bindgen]
#[repr(u32)]
pub enum Drink{
    InkSaverMain = 0,
    InkSaverSub = 1,
    InkRecoveryUp = 2,
    RunSpeedUp = 3,
    SwimSpeedUp = 4,
    SpecialChargeUp = 5,
    SpecialSaver = 6,
    SpecialPowerUp = 7,
    QuickRespawn = 8,
    QuickSuperJump = 9,
    SubPowerUp =10,
    InkResistanceUp =11,
    SubResistanceUp =12,
    IntensifyAction =13,
    None = 0xffffffff
}*/

#[wasm_bindgen(typescript_custom_section)]
const TS_APPEND_CONTENT_LEANNYDRINK: &'static str = 
r#"export enum LeannyDrink{
    InkSaverMain = 0,
    InkSaverSub = 1,
    InkRecoveryUp = 2,
    RunSpeedUp = 3,
    SwimSpeedUp = 4,
    SpecialChargeUp = 5,
    SpecialSaver = 6,
    SpecialPowerUp = 7,
    QuickRespawn = 8,
    QuickSuperJump = 9,
    SubPowerUp =10,
    InkResistanceUp =11,
    SubResistanceUp =12,
    IntensifyAction =13,
    None = 0xff
}"#;
pub enum LeannyDrink{
    InkSaverMain = 0,
    InkSaverSub = 1,
    InkRecoveryUp = 2,
    RunSpeedUp = 3,
    SwimSpeedUp = 4,
    SpecialChargeUp = 5,
    SpecialSaver = 6,
    SpecialPowerUp = 7,
    QuickRespawn = 8,
    QuickSuperJump = 9,
    SubPowerUp =10,
    InkResistanceUp =11,
    SubResistanceUp =12,
    IntensifyAction =13,
    None = 0xff
}

#[wasm_bindgen(typescript_custom_section)]
const TS_APPEND_CONTENT_LEANNYSUBABILITY: &'static str = 
r#"export enum LeannySubAbility{
    InkSaverMain = 0,
    InkSaverSub = 1,
    InkRecoveryUp = 2,
    RunSpeedUp = 3,
    SwimSpeedUp = 4,
    SpecialChargeUp = 5,
    SpecialSaver = 6,
    SpecialPowerUp = 7,
    QuickRespawn = 8,
    QuickSuperJump = 9,
    SubPowerUp =10,
    InkResistanceUp =11,
    SubResistanceUp =12,
    IntensifyAction =13,
    None = 0xff
}"#;
pub enum LeannySubAbility{
    InkSaverMain = 0,
    InkSaverSub = 1,
    InkRecoveryUp = 2,
    RunSpeedUp = 3,
    SwimSpeedUp = 4,
    SpecialChargeUp = 5,
    SpecialSaver = 6,
    SpecialPowerUp = 7,
    QuickRespawn = 8,
    QuickSuperJump = 9,
    SubPowerUp =10,
    InkResistanceUp =11,
    SubResistanceUp =12,
    IntensifyAction =13,
    None = 0xff
}

#[wasm_bindgen(typescript_custom_section)]
const TS_APPEND_CONTENT_MAINABILITY: &'static str = 
r#"export enum MainAbility {
    MainInk_Save = 0,
    SubInk_Save = 1,
    InkRecovery_Up = 2,
    HumanMove_Up = 3,
    SquidMove_Up = 4,
    SpecialIncrease_Up = 5,
    RespawnSpecialGauge_Save = 6,
    SpecialSpec_Up = 7,
    RespawnTime_Save = 8,
    JumpTime_Save = 9,
    SubSpec_Up =10,
    OpInkEffect_Reduction =11,
    SubEffect_Reduction =12,
    Action_Up =13,

    StartAllUp                 = 100,
    EndAllUp                   = 101,
    MinorityUp                 = 102,
    ComeBack                   = 103,

    SquidMoveSpatter_Reduction = 104,
    DeathMarking               = 105,
    ThermalInk                 = 106,
    Exorcist                   = 107,

    SuperJumpSign_Hide         = 109,
    ObjectEffect_Up            = 110,
    SomersaultLanding          = 111
}"#;
pub enum MainAbility {
    MainInk_Save = 0,
    SubInk_Save = 1,
    InkRecovery_Up = 2,
    HumanMove_Up = 3,
    SquidMove_Up = 4,
    SpecialIncrease_Up = 5,
    RespawnSpecialGauge_Save = 6,
    SpecialSpec_Up = 7,
    RespawnTime_Save = 8,
    JumpTime_Save = 9,
    SubSpec_Up =10,
    OpInkEffect_Reduction =11,
    SubEffect_Reduction =12,
    Action_Up =13,

    StartAllUp                 = 100,
    EndAllUp                   = 101,
    MinorityUp                 = 102,
    ComeBack                   = 103,

    SquidMoveSpatter_Reduction = 104,
    DeathMarking               = 105,
    ThermalInk                 = 106,
    Exorcist                   = 107,

    SuperJumpSign_Hide         = 109,
    ObjectEffect_Up            = 110,
    SomersaultLanding          = 111
}

#[declare]
type TicketCombo = Vec<Ticket>;


#[declare]
type AbilityCombo = Vec<SubAbility>;

#[declare]
type TicketSet = Vec<Ticket>;